### ISSUE TITLE
[Question] Defining typed page object throws errors on should

### ISSUE THREAD

**Issue by gabrielthomasjacobs** [jdavis61/webdriverio-typescript-examples#2]
Hello and thank you for creating this repository. It's been extremely helpful and insightful on structuring my testing framework!

I noticed in the login test you've created, you do the following:
```
let loginPage;  
before('setup', () => {  
    const navMenu: NavigationMenu = new NavigationMenu();
    navMenu.loadNavigationMenu();
    loginPage = navMenu.loadFormAuthenticationPage();
});
```

By not importing LoginPage and setting the type, a la:
```
let loginPage: LoginPage;
```
you don't get code completion, but upon specifying the type, I run into errors on the "should" assertions. some ex code:
```
loginPage.getFancyButtonText().should.be.equal('foo');
```
```
Property 'should' does not exist on type 'string'.ts(2339)
```

Do you normally just proceed without the code completion? 
Is the workflow to apply the type, write the test, then remove the type?

Thanks!

edit: since posting, I've figured out that using
```
import * as chai from 'chai';
``` 
fixes the issue (perhaps not the best...), but I am still curious about the decisions you made on what to type/not type. I noticed in the commit history, that at one point you did have loginPage typed and it was removed.

**Comment by jdavis61** [comment]
Hi @gabrielthomasjacobs thank for reaching out. 

RE: "Do you normally just proceed without the code completion?" the answer is yes but I definitely should consider it. Code completion is very important and/or a very helpful convenience in typed languages.

RE: your question about loginPage being typed, I am not sure to be honest because I wrote this code almost 2 years ago. 

Let me look into making the examples "code completion" friendly, also this example should be updated as well. When I finish I will add the branch and you can take a look.

**Comment by jdavis61** [comment]
Hi @gabrielthomasjacobs I added types to the test setup vars to make more code completion friendly. Also upgraded dependencies, removed windows newlines. 

These changes have been uploaded to master, run a `git pull` to see them.  Thanks again for taking a look at this example and for the code completion feedback!

**Comment by gabrielthomasjacobs** [comment]
So fast! Thanks for the quick response and updates. I'm excited to look through it!
